spring.application.name=api

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret=8mVfQ2pKx9ZrT6nY1cW7dH4sJ0aLqP3uN5bGkR2tX6eC9yF1hM7vS4dA0pL8zQ2n
jwt.expiration=600000